### ISSUE TITLE
Question with RAI Function

### ISSUE THREAD

**Issue by LaraVolski** [LaraVolski/bobcats#2]
https://github.com/LaraVolski/bobcats/blob/2068610269c0838fa849bf89e0e79907be6caac8/bobcats_livestockguardiandog_analysis.rmd#L161

Hi Kaitlyn,

Another question to send your way!

When I test out the RAI function, I receive the error: "Error in quos(...) : object 'allclassifications' not found."

I don't know if this is relevant, but there's something up with the 'date' column in 'record.table.all.' In the csv I downloaded from Dropbox, Phase 4 had the time attached to the date. I reformatted this in excel so that only the date would show, but I suspect the metadata may be messing it up, because some of the dates are formatted as and others as '2016-06-15' and any of the dates from Phase 4 are formatted as '1/1/2020.'

Thank you so much!!
Lara

**Comment by kaitlyngaynor** [comment]
Ahh never reformat in Excel! Will mess everything up :) Try to bring it in R and go from there instead. You can always just change the date+time column to date with the as.Date() function

**Comment by kaitlyngaynor** [comment]
My general piece of advice is to just test each line of the RAI function independently like we did last time, with the values that you're interested in, and see what line it breaks on. But the issue to me here actually seems that you just haven't created the object allclassifications in this script. There should have been a line in the script that I sent you that creates an object that contains a list of all possible classifications of animals from Hopland—find that, copy it in, run it before this function and then the object will be found

**Comment by LaraVolski** [comment]
That was an easy fix (: Thanks Kaitlyn!

**Comment by kaitlyngaynor** [comment]
Ahh never reformat in Excel! Will mess everything up :) Try to bring it in R and go from there instead. You can always just change the date+time column to date with the as.Date() function
